cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_3000_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_3000_width1_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_width1_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_width1_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_3000_width50_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_width50_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_width50_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_3000_width100_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_width100_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_width100_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_3000_width200_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_width200_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_width200_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_3000_width300_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_width300_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_width300_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_3000_width500_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_width500_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_width500_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

######4 TeV Zprime###########################
cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_4000_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_3000_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_3000_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/ZprimeToEE_M_4000_width1_Tune4C_13TeV_pythia8_cfi.py --fileout ZprimeToEE_M_4000_width1_Tune4C_13TeV_pythia8_FULLSIM.root --mc --eventcontent AODSIM --datatier GEN-SIM --conditions auto:mc --beamspot Realistic8TeVCollision --step GEN --python_filename ZprimeToEE_M_4000_width1_Tune4C_13TeV_pythia8_FULLSIM_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring -n 20000

